# Desktop Services
exec = $bar
exec = hyprpaper
exec-once = $idle
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Themes
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-light"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface icon-theme 'rose-pine-icons'

# Utilities and Apps
exec-once = nm-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = qs -c overview
