export PATH="/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:/usr/local/sbin:/usr/local/bin"
export PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/scripts"
export PATH="$PATH:$HOME/.cargo/bin:$HOME/labs/dotfiles/bin"
export PATH="$PATH:$HOME/.ebcli-virtual-env/executables"
export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"

export EDITOR="/usr/bin/nano"
export PAGER="/usr/bin/more"

export BUN_INSTALL="$HOME/.local/share/bun"
export CARGO_HOME="$HOME/.local/share/cargo"
export GOPATH="$HOME/.local/share/go"
export NVM_DIR="$HOME/.local/share/nvm"
export ZSH="$HOME/.local/share/oh-my-zsh"
export PM2_HOME="$HOME/.local/share/pm2"
export npm_config_prefix="$HOME/.local/share/npm"
export npm_config_cache="$HOME/.cache/npm"
export OLLAMA_HOME="$HOME/.local/share/ollama"
export DOTNET_CLI_HOME="$HOME/.local/share/dotnet"
export ANDROID_USER_HOME="$HOME/.local/share/android"

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
DOTFILESSRC="$HOME/labs/dotfiles"
ANDROID_HOME='/home/ali/Android/Sdk'

if [[ "$(uname)" == "Darwin" ]]; then
  HOSTMACHINE="discobot"
  export JAVA_HOME='/Applications/Android Studio.app/Contents/jbr/Contents/Home'
  export ANDROID_HOME='/Users/ali/Library/Android/sdk'
fi