-- Workspace assignments are per-host — see lua/hosts/<hostname>.lua.
--
-- This file used to carry "default" rules for two placeholder monitors; every
-- real host overrode the ones it used, and the leftovers actively misbehaved:
-- on k3v1n, workspaces 10-12 came out pinned to h4l9000's OLED panel (a
-- monitor that machine will never see), so they were never persistent and the
-- e±1 cycle and overview treated them inconsistently. A default that no host
-- uses and one host is hurt by is not a default; each host declares its own
-- full set now (k3v1n 1-9, mcu 1-10, h4l9000 1-12).
